/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordleGame.model;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testSecretWordClass() {
        SecretWordTest secretWordTest = new SecretWordTest();
    }
}
